name: Compile Mobile Java 25 for iOS
on:
  workflow_dispatch:

jobs:
  build:
    name: Compile Darwin Aarch64
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Apple Building SDKs
        run: |
          brew install autoconf make wget xz
          
      - name: Clone Mobile-Patched OpenJDK Source
        run: |
          git clone --depth 1 -b master https://github.com openjdk-src

      - name: Configure and Build
        run: |
          cd openjdk-src
          sh configure --openjdk-target=aarch64-apple-darwin --with-debug-level=release --with-jvm-variants=zero
          /opt/homebrew/bin/gmake images
          tar -czf ../openjdk-25-darwin-arm64.tar.gz build/*/images/jdk

      - name: Upload Java 25 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openjdk-25-darwin-arm64
          path: openjdk-25-darwin-arm64.tar.gz



