name: Custom Java 25 Build
on:
  workflow_dispatch:

jobs:
  build:
    name: Build JRE
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Homebrew and Build Tools
        run: |
          # Download the tools the server is missing
          brew install make wget xz
          
      - name: Run Build Script
        run: |
          export SLIMMED=0
          # Tell it exactly where the new gmake tool is located
          /opt/homebrew/bin/gmake -j$(sysctl -n hw.ncpu) package PLATFORM=2
